# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  #bundle exec fastlane send_to_testers
  desc "Sending version to Guillaume"
  lane :send_to_testers do

    sh("cd ../../../pokemon_new && flutter clean")
    sh("cd ../../../pokemon_new && flutter pub get")
    sh("cd ../../../pokemon_new && flutter build apk --release")

    firebase_app_distribution(
      app: "1:865249701318:android:90bb223e6fbfba08fbd6c7",
      apk_path: "/home/mayeut/dev/flutter_workspace/pokemon_new/pokemon_new/build/app/outputs/flutter-apk/app-release.apk",
      release_notes: "New version from Fastlane",
      testers: "mayeut@gmail.com,gbalas.sup@gmail.com"
    )
  end

  #bundle exec fastlane send_to_me
    desc "Sending version to me"
    lane :send_to_me do

      sh("cd ../../../pokemon_new && flutter clean")
      sh("cd ../../../pokemon_new && flutter pub get")
      sh("cd ../../../pokemon_new && flutter build apk --release")

      firebase_app_distribution(
        app: "1:865249701318:android:90bb223e6fbfba08fbd6c7",
        apk_path: "/home/mayeut/dev/flutter_workspace/pokemon_new/pokemon_new/build/app/outputs/flutter-apk/app-release.apk",
        release_notes: "New version from Fastlane",
        testers: "mayeut@gmail.com"
      )
    end
end
